### PR TITLE
Upstream Patches

### PR DESCRIPTION
**Pull request by rexjohannes**
Upstream Patches

### CODE REVIEW

**Comment by taynotfound** [comment]
What exactly does this Pull Request?

**Comment by taynotfound** [comment]
And please fix the Conflicts (keep in mind to not remove earlier made changes that might not be in the newer src)

**Comment by rexjohannes** [comment]
Sorry, but i have no Wirte Permissions to fix conflicts

**Comment by taynotfound** [comment]
Then fix them in your Fork of our Discord.js and make a PR with that please

**Comment by ImFelixprogram** [comment]
Hello @rexjohannes ,

this commit list is way to mixed up. Next time, please split this up into multiple pull requests with clear documentation of the changes and its' use to this project.
Well, although I've looked into it and looking at the commits, they seem to match with the commits on the official discord.js repository, as you've seen, merging those with our repository will cause conflicts because we've edited this repository ourselves and it doesn't match with the official discord.js repository anymore.
We will merge those commits, keeping our edits, manually when we have time or need any of the added functionality on those commits - or, as Tayron said, if you want, you can fix those conflicts by yourself and try again to open a pull request.

~ Felixprogram, CTO of Little Studios

**Pull request closed without merging**
